[package]
name = "serial_ecs"
version = "0.1.0"
authors = ["nokevair <64569057+nokevair@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vec_map = "0.8.2"
